# Generated by Django 5.0.2 on 2024-04-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="GoogleForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_link", models.URLField()),
                ("post_link", models.URLField()),
                ("mid_link", models.URLField()),
            ],
        ),
    ]
