# Generated by Django 4.1.13 on 2024-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarox", "0002_formsubmission_googleform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ammounts",
            field=models.BigIntegerField(blank=True),
        ),
    ]
